/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE TASK1_TYPES PACKING
package com.MAVLink.task1;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Test all field types
*/
public class msg_task1_types extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_TASK1_TYPES = 181;
    public static final int MAVLINK_MSG_ID_TASK1_TYPES_CRC = 71;
    public static final int MAVLINK_MSG_LENGTH = 14;
    private static final long serialVersionUID = MAVLINK_MSG_ID_TASK1_TYPES;


      
    /**
    * Latitude (WGS84), in degrees * 1E7
    */
    public long latitude;
      
    /**
    * Longitude (WGS84), in degrees * 1E7
    */
    public long longitude;
      
    /**
    * Altitude (AMSL), in meters * 1000 (positive for up)
    */
    public long altitude;
      
    /**
    * plane id
    */
    public short flag;
      
    /**
    * plane number
    */
    public short number;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_TASK1_TYPES;
        packet.crc_extra = MAVLINK_MSG_ID_TASK1_TYPES_CRC;
              
        packet.payload.putUnsignedInt(latitude);
              
        packet.payload.putUnsignedInt(longitude);
              
        packet.payload.putUnsignedInt(altitude);
              
        packet.payload.putUnsignedByte(flag);
              
        packet.payload.putUnsignedByte(number);
        
        return packet;
    }

    /**
    * Decode a task1_types message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.latitude = payload.getUnsignedInt();
              
        this.longitude = payload.getUnsignedInt();
              
        this.altitude = payload.getUnsignedInt();
              
        this.flag = payload.getUnsignedByte();
              
        this.number = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_task1_types(){
        msgid = MAVLINK_MSG_ID_TASK1_TYPES;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_task1_types(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_TASK1_TYPES;
        unpack(mavLinkPacket.payload);
    }

              
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_TASK1_TYPES - sysid:"+sysid+" compid:"+compid+" latitude:"+latitude+" longitude:"+longitude+" altitude:"+altitude+" flag:"+flag+" number:"+number+"";
    }
}
        